### ISSUE TITLE
Unable to run the game

### ISSUE THREAD

**Issue by nmanumr** [igormilla/phaserjs-snake-game#1]
I tried it from http://igormilla.github.io/phaserjs-snake-game/ and slod after clone.
but the game stuck after writing "SNAKE" on canvas

**Comment by igormilla** [comment]
I just tried to run it from the url you posted, and it does work for me. 
Have you clicked the 'space bar' to start the game? 
What OS/browser do you use? It will definitely not work on mobile device.
Any errors in Dev tools?

**Comment by nmanumr** [comment]
I am using Windows 10 and Chrome v58

**Comment by nmanumr** [comment]
Here is the screen shot of dev tools
![image](https://cloud.githubusercontent.com/assets/19629102/25494597/96fd678e-2b93-11e7-809c-e70d1c0daa9a.png)

**Comment by igormilla** [comment]
It seems that's that for some reason your browser is blocking loading of google analytics. Do you have some adblocker plugins or some firewall? 
Well i don't really need it there, so I removed it from the page. Can you try again, and see if the game loading for you now?

**Comment by igormilla** [comment]
@naumanumer do you still have issues running the code?
